version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run: docker compose build


workflows:
  version: 2
  ci:
    jobs:
      - test