version: 2.1

jobs:
  test-current:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run: docker compose build
  test-stable:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run: docker compose build


workflows:
  version: 2
  ci:
    jobs:
      - test-stable
      - test-current
