version: 2.1

jobs:
  build:
    parameters:
      runner-tag:
        type: string
      remote-docker-version:
        type: string
    docker:
      - image: cimg/base:<< parameters.runner-tag >>
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: << parameters.remote-docker-version >>
      - run: docker compose build
  prebuild:
    parameters:
      runner-tag:
        type: string
      remote-docker-version:
        type: string
    docker:
      - image: cimg/base:<< parameters.runner-tag >>
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: << parameters.remote-docker-version >>
      - run: docker build -t local-hello .
      - run: docker compose -f prebuild.docker-compose.yml build

workflows:
  version: 2
  ci:
    jobs:
      - build:
          matrix:
            parameters:
              runner-tag: [stable, current, edge]
              remote-docker-version: [20.10.12,20.10.11,20.10.7,20.10.6,20.10.2,19.03.13,17.09.0-ce]
      - prebuild:
          matrix:
            parameters:
              runner-tag: [stable, current, edge]
              remote-docker-version: [20.10.12,20.10.11,20.10.7,20.10.6,20.10.2,19.03.13,17.09.0-ce]
